language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
# - "pypy3"
# command to install dependencies
install:
  - pip install -r requirements.txt -r test-requirements.txt
# command to run tests
script:
  - coverage run --source src/tdclient setup.py test
  - coverage report
after_success:
  - coveralls
